---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: "https://kubernetes.default.svc"
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - FailOnSharedResource=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 5
        maxDuration: 10m
  source:
    repoURL: "https://charts.jetstack.io"
    targetRevision: "~v1.11.0"
    chart: "cert-manager"
    helm:
      releaseName: cert-manager
      values: |-
        installCRDs: true
        enableCertificateOwnerRef: true
        prometheus:
          enabled: true
          servicemonitor:
            enabled: true
