---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-dns
    server: "https://kubernetes.default.svc"
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - FailOnSharedResource=true
    retry:
      limit: 15
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
  source:
    repoURL: "https://kubernetes-sigs.github.io/external-dns/"
    targetRevision: "~1.15.2"
    chart: "external-dns"
    helm:
      releaseName: external-dns
      valuesObject:
        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflare-api-token
                key: api-token
        logLevel: debug
        extraArgs:
          - --publish-internal-services
        provider: cloudflare
        domainFilters:
          - iakimenko.me.
          - iakimenko.me
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
