---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ingress-nginx
    server: "https://kubernetes.default.svc"
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - FailOnSharedResource=true
    retry:
      limit: 15
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
  source:
    repoURL: "https://kubernetes.github.io/ingress-nginx"
    targetRevision: "~4.12.0"
    chart: "ingress-nginx"
    helm:
      releaseName: ingress-nginx
      valuesObject:
        controller:
          image:
            readOnlyRootFilesystem: true
          publishService:
            enabled: true
          allowSnippetAnnotations: false
          config:
            ssl-redirect: "true"
            force-ssl-redirect: "true"
          #   global-auth-url: ""
          #   global-auth-method: ""
        rbac:
          create: true
          createClusterRole: true
          createRole: true
        tcp:
          "26656": "cosmos/cosmos:26656"
