version: 2.1

jobs:

  check:
    docker:
      - image: alpine/terragrunt:1.10.3
    steps:
      - checkout
      - run:
          name: Setup HCP Terraform Token
          command: |
            echo "export TF_TOKEN_app_terraform_io=$HCP_TOKEN" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Check Terraform Formatting
          command: |-
            cd ./terraform
            terragrunt run-all fmt --terragrunt-non-interactive --check
      - run:
          name: Validate Terraform Configuration
          command: |-
            cd ./terraform
            terragrunt run-all validate --terragrunt-non-interactive

  apply-base:
    docker:
      - image: alpine/terragrunt:1.10.3
    steps:
      - checkout
      - run:
          name: Setup HCP Terraform Token
          command: |
            echo "export TF_TOKEN_app_terraform_io=$HCP_TOKEN" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Plan Terraform Changes
          command: |-
            cd ./terraform/base
            terragrunt run-all plan --terragrunt-non-interactive -out=tfplan
      - run:
          name: Apply Terraform Changes
          command: |-
            cd ./terraform/base
            terragrunt run-all apply --terragrunt-non-interactive tfplan

  apply-content:
    docker:
      - image: alpine/terragrunt:1.10.3
    steps:
      - checkout
      - run:
          name: Setup HCP Terraform Token
          command: |
            echo "export TF_TOKEN_app_terraform_io=$HCP_TOKEN" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Plan Terraform Changes
          command: |-
            cd ./terraform/content
            terragrunt run-all plan --terragrunt-non-interactive -out=tfplan
      - run:
          name: Apply Terraform Changes
          command: |-
            cd ./terraform/content
            terragrunt run-all apply --terragrunt-non-interactive tfplan

workflows:
  terraform:
    when: { equal: [ api, << pipeline.trigger_source >> ] }
    jobs:
      - check
      - apply-base:
          requires:
            - check
      - apply-content:
          requires:
            - apply-base
