---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: cosmos
  name: cosmos
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cosmos
  serviceName: cosmos
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cosmos
    spec:
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
        supplementalGroups: [65534]
      shareProcessNamespace: false
      enableServiceLinks: false
      volumes:
        - emptyDir: {}
          name: emptydir
        - name: init-sh
          configMap:
            name: init-sh
            defaultMode: 0777
      initContainers:
        - name: init-cosmos
          image: ghcr.io/cosmos/gaia:v22.3.0
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            privileged: false
            readOnlyRootFilesystem: true
          env:
            - name: HOME
              value: /gaia
          command: ["sh", "-c"]
          args:
            - |-
              if ! [ -f "$HOME/._Mark" ]; then
                $HOME/init.sh
                touch "$HOME/._Mark"
              fi
          volumeMounts:
            - mountPath: /tmp
              name: emptydir
            - name: data
              mountPath: /gaia
            - name: init-sh
              mountPath: /gaia/init.sh
              subPath: init.sh
      containers:
        - name: cosmos
          image: ghcr.io/cosmos/gaia:v22.3.0
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            privileged: false
            readOnlyRootFilesystem: true
          env:
            - name: HOME
              value: /gaia
          command: ["sh"]
          stdin: true
          tty: true
          # args:
          #   - |-
          #     gaiad start --x-crisis-skip-assert-invariants --home $HOME
          ports:
            - containerPort: 26657
              name: rpc
          volumeMounts:
            - mountPath: /tmp
              name: emptydir
            - name: data
              mountPath: "/gaia"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
