---
createAggregateRoles: true
configs:
  cm:
    admin.enabled: false
    users.anonymous.enabled: "true"
    server.rbac.log.enforce.enable: "true"
    url: "https://argocd.iakimenko.link"
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: $argocd-github-oauth:client-id
            clientSecret: $argocd-github-oauth:client-secret
            orgs:
              - name: kroche-co
    application.links: &links |
      - url: {{.metadata.annotations.a8r\.io\/logs}}
        title: Logs
        if: metadata.annotations.a8r\.io\/logs
      - url: {{.metadata.annotations.a8r\.io\/documentation}}
        title: Documentation
        if: metadata.annotations.a8r\.io\/documentation
      - url: {{.metadata.annotations.a8r\.io\/repository}}
        title: Repository
        if: metadata.annotations.a8r\.io\/repository
      - url: {{.metadata.annotations.a8r\.io\/performance}}
        title: Monitoring
        if: metadata.annotations.a8r\.io\/performance
    resource.links: *links
    resource.customizations: |
      argoproj.io/Application:
        health.lua: |
          hs = {}
          hs.status = "Progressing"
          hs.message = ""
          if obj.status ~= nil then
            if obj.status.health ~= nil then
              hs.status = obj.status.health.status
              if obj.status.health.message ~= nil then
                hs.message = obj.status.health.message
              end
            end
          end
          return hs
    statusbadge.enabled: "true"
  params:
    application.namespaces: "*"
    server.enable.gzip: true
  repositories:
    argocd-cluster:
      type: "git"
      url: "https://github.com/kukaryambik/do-cluster.git"
      project: "default"
  rbac:
    create: true
    policy.default: "role:guest"
    policy.csv: |
      g, kroche-co:infra, role:admin
      p, role:readonly, logs, *, *, allow
      p, role:guest, applications, get, *, allow
      p, role:guest, applicationsets, get, *, allow
      p, role:guest, clusters, get, *, allow
      p, role:guest, projects, get, *, allow
      p, role:guest, repositories, get, *, allow
    scopes: "[groups]"
controller:
  clusterAdminAccess:
    enabled: true
server:
  clusterAdminAccess:
    enabled: true
repoServer:
  clusterAdminAccess:
    enabled: true
dex:
  enabled: true
